TinkerAppProject/Controllers/ChartingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TinkerAppProject.Areas.Identity.Data;
using TinkerAppProject.Models.Charting;
using TinkerAppProject.Services.Charting;

namespace TinkerAppProject.Controllers
{
    [Authorize]
    public class ChartingController : Controller
    {
        private IChartGenerationService _chartGenerationService;
        private readonly UserManager<TinkerAppProjectUser> _userManager;

        public ChartingController(IChartGenerationService chartGenerationService, UserManager<TinkerAppProjectUser> userManager)
        {
            _chartGenerationService = chartGenerationService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GenerateChart(ChartModel model)
        {
            var userId = _userManager.GetUserId(User);
            var result = new ChartResponse();
            result = await _chartGenerationService.GenerateChartByMonths(model, userId);
            return View(result);
        }
    }
}

TinkerAppProject/Controllers/ExpensesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TinkerAppProject.Areas.Identity.Data;
using TinkerAppProject.Models.Expenses;
using TinkerAppProject.Repositories;

namespace TinkerAppProject.Controllers
{
    [Authorize]
    public class ExpensesController : Controller
    {
        private readonly IExpenseRepository _expenseRepository;
        private readonly UserManager<TinkerAppProjectUser> _userManager;
        private readonly ILogger<ExpensesController> _logger;

        public ExpensesController(IExpenseRepository expenseRepository, UserManager<TinkerAppProjectUser> userManager, ILogger<ExpensesController> logger)
        {
            _expenseRepository = expenseRepository;
            _userManager = userManager;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchString)
        {
            var expenses = new ExpensesViewModel();
            try
            {
                var user = await _userManager.GetUserAsync(User);

                if (string.IsNullOrEmpty(searchString))
                {
                    var allExpenses = await _expenseRepository.GetAllExpensesByUser(user.Id);
                    expenses.Expenses.AddRange(allExpenses);
                }
                else
                {
                    var filteredExpenses = await _expenseRepository.GetExpensesByConceptAsync(searchString, user.Id);
                    expenses.Expenses.AddRange(filteredExpenses);
                }

                return View(expenses);
            }
            catch (Exception ex)
            {
                ViewBag.Exception = "Error loading user expenses. Message: " + ex.Message;
                _logger.LogError(ex, "Error loading user expenses.");
                return View("CreateExpenseError");
            }
        }

        public IActionResult CreateExpenseIndex()
        {
            return View(new ExpenseModel() { DayPaid = DateTime.Today});
        }

        public async Task<IActionResult> EditExpenseIndex(Guid expenseGuid)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            var model = await _expenseRepository.GetExpenseById(expenseGuid);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateExpense(ExpenseModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            int response;
            try
            {
                var user = await _userManager.GetUserAsync(User);

                if (user == null)
                {
                    return RedirectToAction("Index");
                }
                model.UserId = user.Id;
                model.UserName = user.UserName;
                model.User = user;
                response = await _expenseRepository.CreateExpense(model);
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, "Error creating new expense.");
                ViewBag.Exception = "Error creating new expense. Message: " + ex.Message;
                return View("CreateExpenseError");
            }

            return response == 1 ? View("CreateExpenseSuccess") : View("CreateExpenseError");
        }

        public async Task<IActionResult> EditExpense(ExpenseModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            try
            {
                var response = await _expenseRepository.UpdateExpense(model);
                if (response == 1)
                {
                    return View("CreateExpenseSuccess");
                }
                else
                {
                    throw new Exception("Couldn't update expense.");
                }
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, "Error updating expense.");
                ViewBag.Exception = "Error updating expense. Message: " + ex.Message;
                return View("CreateExpenseError");
            }

        }
        
        public async Task<IActionResult> DeleteExpense(Guid expenseGuid)
        {
            return await _expenseRepository.DeleteExpense(expenseGuid) == 1 ? RedirectToAction("Index") : View("CreateExpenseError");
        }
    }
}

TinkerAppProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TinkerAppProject</title>
    <link rel="icon" href="~/lib/img/tinkerpiggy.png" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TinkerAppProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 blue-palette">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/lib/img/logo-transparent.png"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Charting" asp-action="Index">Graph Analytics</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TinkerAppProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>